### ISSUE TITLE
Simplify signing commits, remove dependency on `crazy-max/ghaction-import-gpg`

### ISSUE THREAD

**Issue by morancj** [weaveworks/pipeline-controller#113]
https://github.com/weaveworks/pipeline-controller/pull/102#discussion_r1026381765

```yaml
- name: Configure GPG Key
  run: |
    echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
  env:
    GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
```

Would obviate #108. :slightly_smiling_face:
