### ISSUE TITLE
Create promotion PR for next environment

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/pipeline-controller#33]
Add/update `promotion` field used to capture the promotion task for the next environment in the pipeline after a successful deployment has taken place.

```yaml
apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo
  namespace: default
spec:
  promotion:
    pull-request:
      url: ssh://git@github.com/organization/repo
      branch: main
      secretRef: my-other-deployed-secret
[...]
```

Details of the field are defined in RFC 3 as part of [this PR](https://github.com/weaveworks/weave-gitops-private/pull/76).

- [x] #37 
- [x] #48
- [x] #49

## Notes

We already use `go-git-providers` to create PRs [in WGE](https://github.com/weaveworks/weave-gitops-enterprise/blob/main/cmd/clusters-service/pkg/git/git.go) so we should reuse the same package to support the same git providers.
